FROM node:20-alpine

WORKDIR /app
COPY backend/package*.json ./
RUN npm install --omit=dev
COPY backend/src ./src
COPY backend/scripts ./scripts

ENV NODE_ENV=production
CMD ["npm", "run", "db:migrate"]
