CREATE TABLE IF NOT EXISTS lesson_observations (
    id SERIAL PRIMARY KEY,
    observation_date DATE NOT NULL,
    teacher_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR(255) NOT NULL,
    class_name VARCHAR(100) NOT NULL,
    students_total INTEGER NOT NULL,
    students_attended INTEGER NOT NULL,
    topic VARCHAR(500) NOT NULL,
    lesson_type VARCHAR(255),
    evaluation VARCHAR(255),
    kmj_standard TEXT,
    organization TEXT,
    homework TEXT,
    teacher_student_relation TEXT,
    new_lesson_explanation TEXT,
    topic_reveal TEXT,
    teaching_methods TEXT,
    task_delivery TEXT,
    feedback TEXT,
    conclusion TEXT,
    photo_url VARCHAR(500),
    filled_by_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
